import "@/styles/globals.css"

import { Inter } from "next/font/google"
import {
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

import { TRPCReactProvider } from "@/trpc/react"
import { ClerkProvider } from "@clerk/nextjs"
import Navbar from "@/components/ui/navbar"

const inter = Inter({
  subsets: ["latin"],
})

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={inter.className}>
          <TRPCReactProvider>
            <Navbar />
            {children}
            <body>
              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </body>
          </TRPCReactProvider>
        </body>
      </ClerkProvider>
    </html>
  )
}