import { MainSidebar } from "@/components/mainSideBar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Suspense } from "react";

export const metadata = {
  title: "Dashboard",
  description: "Generated by team gold",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function ProtectedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <div className="flex h-screen">
        <SidebarProvider>
      <AppSidebar />
      <main>
            <SidebarTrigger />
            <div className="px-10 py-5">
        {children}

            </div>
      </main>
    </SidebarProvider>
      </div>
    </main>
  );
}
