import { Suspense } from "react";

export const metadata = {
  title: "Dashboard",
  description: "Generated by team gold",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function ProtectedLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <div className="flex h-screen">
        <Suspense fallback={<div>Loading...</div>}>
          {/*   <MainSidebar /> */}
        </Suspense>
        <div className="flex w-full flex-col">{children}</div>
      </div>
    </main>
  );
}
